version: '2'
services:
    demo_jhipster-app:
        image: demo_jhipster
        external_links:
            - demo_jhipster-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/demo_jhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo_jhipster-postgresql:
        extends:
            file: postgresql.yml
            service: demo_jhipster-postgresql
